Don't expect BLK error with un-parsable mixed tabs
$ flake8  tests/test_cases/mixed_tab_spaces.py
tests/test_cases/mixed_tab_spaces.py:8:1: W191 indentation contains tabs
tests/test_cases/mixed_tab_spaces.py:8:1: E101 indentation contains mixed spaces and tabs
tests/test_cases/mixed_tab_spaces.py:8:44: E999 TabError: inconsistent use of tabs and spaces in indentation

$ black --check tests/test_cases/mixed_tab_spaces.py
error: cannot format tests/test_cases/mixed_tab_spaces.py: cannot use --safe with this file; failed to parse source file with Python 3.7's builtin AST. Re-run with --fast or stop using deprecated Python 2 syntax. AST error message: inconsistent use of tabs and spaces in indentation (<unknown>, line 8)
All done! 💥 💔 💥
1 file would fail to reformat.